[package]
name = "cp-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
